version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "6566:1433" #For login by SSMS -> .,6566
    volumes:
      - sqlvolume:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10

  notification-api:
    build:
      context: ./Tajan.Notification.API
      dockerfile: Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDb;User Id=sa;Password=YourStrong!Passw0rd;
    ports:
      - "5000:80"

  product-api:
    build:
      context: ./Tajan.ProductService.API
      dockerfile: Dockerfile
    depends_on:
      - notification-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDb;User Id=sa;Password=YourStrong!Passw0rd;
    ports:
      - "5001:80"
volumes:
  sqlvolume:
